In [1]:
import sys
sys.path.insert(0, r'C:\Users\Acer\Desktop\lampix glass dettect\models\research')
sys.path.insert(0, r'C:\Users\Acer\Desktop\lampix glass dettect\models')
print(sys.path)

['C:\\Users\\Acer\\Desktop\\lampix glass dettect\\models', 'C:\\Users\\Acer\\Desktop\\lampix glass dettect\\models\\research', 'C:\\Users\\Acer\\Desktop\\lampix glass dettect', 'C:\\Users\\Acer\\anaconda3\\python38.zip', 'C:\\Users\\Acer\\anaconda3\\DLLs', 'C:\\Users\\Acer\\anaconda3\\lib', 'C:\\Users\\Acer\\anaconda3', '', 'C:\\Users\\Acer\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages', 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Acer\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Acer\\.ipython']


In [2]:
import matplotlib
import matplotlib.pyplot as plt

import os
import random
import io
import imageio
import glob
import scipy.misc
import numpy as np
from six import BytesIO
from PIL import Image, ImageDraw, ImageFont
from IPython.display import display, Javascript
from IPython.display import Image as IPyImage

import tensorflow as tf

from object_detection.utils import label_map_util
from object_detection.utils import config_util
from object_detection.utils import visualization_utils as viz_utils
#from object_detection.utils import colab_utils
from object_detection.builders import model_builder

In [13]:
import glob
import json
import ntpath
from pathlib import Path

def aggregate_jsons(save_file = False):
    res = {}
    classes = {}
    no_class = 0
    for fn in glob.glob(r"C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\*.json"):
        f = open(fn)
        s = f.read()
        o = json.loads(s)
        deletes = []
        for k in o:
            print(k)
            if len(o[k]["regions"]) == 0:
                #print(fn, " -> ", k)
                deletes.append(k)
            else:
                for r in o[k]["regions"]:
                    if "Type" in o[k]["regions"][r]["region_attributes"]:
                        c = o[k]["regions"][r]["region_attributes"]["Type"].lower().strip()
                        if c in classes:
                            classes[c] += 1
                        else:
                            classes[c] = 1
                    elif "type" in o[k]["regions"][r]["region_attributes"]:
                        c = o[k]["regions"][r]["region_attributes"]["type"]
                        if c in classes:
                            classes[c] += 1
                        else:
                            classes[c] = 1                            
                    else:
                        no_class += 1

        #print(len(deletes))
        for k in deletes:
            del o[k]
            
        res.update(o)
        #if s.find("00084.jpg") > 0:
        #    # print(ntpath.basename(fn), " for ", s)
        #    sz = Path("/home/mihai/src/data/TDB_M-20201114T103840Z-001/TDB_M/00084.jpg").stat().st_size
        #    print(res["00084.jpg" + str(sz)])
        #    print("00084.jpg" + str(sz))
        #    break
        f.close()

    print("region classes:", classes)
    print("no class for", no_class, "regions")
    
    if save_file:
        f = open("bigjson.json", "w")
        f.write(json.dumps(res))
        f.close()
    return res, classes


In [14]:
aggregate_jsons()

0001.jpg.png1271009
00002.jpg338727
00003.jpg301598
00004.jpg294643
00005.jpg299565
00006.jpg305176
00007.jpg301325
00008.jpg303852
00009.jpg287445
00010.jpg312631
00011.jpg328677
00012.jpg342041
00013.jpg342420
00014.jpg327238
00015.jpg338018
00016.jpg336979
00017.jpg344794
00018.jpg356870
00019.jpg365775
00020.jpg345683
00021.jpg341824
00022.jpg334768
00023.jpg315607
00024.jpg324922
00025.jpg312964
00026.jpg343717
00027.jpg281740
00028.jpg294184
00029.jpg326378
00030.jpg318492
00031.jpg290957
00032.jpg305763
00033.jpg336930
00034.jpg328064
00035.jpg332427
00036.jpg334673
00037.jpg330278
00038.jpg342544
00039.jpg307042
00040.jpg314711
00041.jpg293315
00042.jpg299656
00043.jpg298839
00044.jpg299188
00045.jpg276509
00046.jpg274062
00047.jpg311329
00048.jpg318393
00049.jpg323989
00050.jpg325713
00051.jpg304481
00052.jpg310114
00053.jpg319758
00054.jpg314021
00055.jpg316804
00056.jpg316923
00057.jpg314605
00058.jpg316491
00059.jpg293060
00060.jpg291442
00061.jpg270379
00062.jpg269233
0006

00614.jpg340515
00615.jpg340298
00616.jpg342630
00617.jpg348695
00618.jpg358352
00619.jpg349460
00620.jpg350241
00621.jpg343948
00622.jpg347729
00623.jpg350334
00624.jpg347554
00625.jpg175487
00626.jpg344105
00627.jpg356735
00628.jpg346443
00629.jpg347296
00630.jpg353971
00631.jpg353273
00632.jpg353170
00633.jpg351792
00634.jpg349201
00635.jpg346538
00636.jpg346469
00637.jpg443474
00638.jpg448035
00639.jpg446695
00640.jpg448627
00641.jpg446200
00642.jpg449077
00643.jpg448672
00644.jpg447655
00645.jpg447681
00646.jpg447489
00647.jpg444401
00648.jpg447079
00649.jpg446397
00650.jpg444136
00651.jpg446489
00652.jpg443567
00653.jpg442693
00654.jpg442062
00655.jpg442456
00656.jpg438498
00657.jpg442017
00658.jpg441796
00659.jpg442995
00660.jpg444040
00661.jpg443032
00662.jpg440845
00663.jpg441518
00664.jpg439251
00665.jpg440718
00666.jpg440009
00667.jpg442544
00668.jpg442503
00669.jpg442211
00670.jpg442678
00671.jpg441213
00672.jpg443163
00673.jpg440550
00674.jpg437813
00675.jpg442331
00676.jp

01542.jpg426561
01543.jpg425581
01544.jpg426448
01545.jpg432292
01546.jpg426363
01547.jpg431562
01548.jpg426094
01549.jpg434041
01550.jpg432154
01551.jpg442244
01552.jpg443111
01553.jpg432613
01554.jpg434020
01555.jpg432173
01556.jpg438239
01557.jpg442883
01558.jpg436673
01559.jpg431796
01560.jpg434471
01561.jpg453293
01562.jpg445609
01563.jpg444852
01564.jpg443455
01565.jpg440183
01566.jpg436192
01567.jpg438236
01568.jpg437678
01569.jpg437062
01570.jpg431371
01571.jpg439385
01572.jpg434183
01573.jpg439190
01574.jpg434525
01575.jpg437704
01576.jpg433151
01577.jpg438081
01578.jpg440029
01579.jpg434230
01580.jpg446529
01581.jpg430134
01582.jpg437882
01583.jpg439292
01584.jpg441404
01585.jpg437503
01586.jpg434533
01587.jpg433833
01588.jpg443045
01589.jpg434962
01590.jpg434960
01591.jpg435572
01592.jpg433153
01593.jpg444900
01594.jpg443728
01595.jpg442756
01596.jpg434366
01597.jpg435447
01598.jpg440784
01599.jpg433281
01600.jpg436014
01601.jpg435171
01602.jpg433998
01603.jpg430877
01604.jp

({'00051.jpg304481': {'fileref': '',
   'size': 304481,
   'filename': '00051.jpg',
   'base64_img_data': '',
   'file_attributes': {},
   'regions': {'0': {'shape_attributes': {'name': 'rect',
      'x': 478,
      'y': 644,
      'width': 262,
      'height': 290},
     'region_attributes': {'Type': 'glass', 'Fill': '0'}},
    '1': {'shape_attributes': {'name': 'rect',
      'x': 1062,
      'y': 429,
      'width': 637,
      'height': 587},
     'region_attributes': {'Type': 'plate', 'Fill': '0'}}}},
  '00052.jpg310114': {'fileref': '',
   'size': 310114,
   'filename': '00052.jpg',
   'base64_img_data': '',
   'file_attributes': {},
   'regions': {'0': {'shape_attributes': {'name': 'rect',
      'x': 609,
      'y': 423,
      'width': 238,
      'height': 223},
     'region_attributes': {'Type': 'glass', 'Fill': '0'}},
    '1': {'shape_attributes': {'name': 'rect',
      'x': 786,
      'y': 629,
      'width': 250,
      'height': 390},
     'region_attributes': {'Type': 'glass'

In [4]:
from pathlib import Path
from PIL import Image
from numpy import asarray
import ntpath
import cv2

category_index = {}

def load_data():
    train_images_np = []
    num = 0
    num_empty = 0
    data, classes = aggregate_jsons()
    
    label_id_offset = 1
    train_image_tensors = []
    gt_classes_one_hot_tensors = []
    gt_box_tensors = []
    category_by_name = {}
    
    n = 1
    for c in classes:
        category_index[n] = {'id': n, 'name': c}
        category_by_name[c] = n
        n += 1
    
    num_classes = len(classes)
       
    for fn in glob.glob(r"C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\*.jpg"):
        sz = Path(fn).stat().st_size
        # load the image
        bname = ntpath.basename(fn)
        k = bname + str(sz)
        if k in data:
            if len(data[k]['regions']) == 0:
                print(bname, ": 0")
            else:
                img = asarray(Image.open(fn))
                res_y = img.shape[0]
                res_x = img.shape[1]
                boxes = []
                classes = []
                scores = []
                for r in data[k]['regions']:
                    ra = data[k]['regions'][r]["region_attributes"]
                    if "type" in ra:
                        cls = ra["type"].lower().strip()
                    elif "Type" in ra:
                        cls = ra["Type"].lower().strip()
                    else:
                        continue
                    
                    rg = data[k]['regions'][r]['shape_attributes']
                    npr = [rg['y']/res_y, rg['x']/res_x, (rg['y'] + rg['height'])/res_y, (rg['x'] + rg['width'])/res_x]
                    boxes.append(npr)
                    classes.append(category_by_name[cls])
                    scores.append(1.0)
                    break
                    
                if(len(boxes) >= 1):
                    #print("classes are ", classes, "and we have", len(boxes), "boxes")
                    train_image_tensors.append(tf.expand_dims(tf.convert_to_tensor(img, dtype=tf.float32), axis=0))
                    gt_box_tensors.append(tf.convert_to_tensor(boxes, dtype=tf.float32))
                    zero_indexed_groundtruth_classes = tf.convert_to_tensor(
                       np.array(classes, dtype=np.int32) - label_id_offset)
                    gt_classes_one_hot_tensors.append(tf.one_hot(zero_indexed_groundtruth_classes, num_classes))
                else:
                    print("BAMMMM")
                
                #ori_image = np.ones([360, 480, 3], dtype=np.int32) * 200
                #test_image = img.copy()
                #boxes = np.array(boxes, dtype=np.float32)
                #classes = np.array(classes, dtype=np.int32)
                #detections = np.ones(len(classes))
                #i = viz_utils.visualize_boxes_and_labels_on_image_array(
                #  test_image, boxes, classes, detections,
                #  category_index,
                #  use_normalized_coordinates=True,
                #  min_score_thresh=0.3)
                #cv2.imwrite("img.jpg", i)
        else:
            print("no region data for ", k)
            num_empty += 1

        num += 1
        
        if num > 300: break
            
            
    print("empty ", num_empty)
    return train_image_tensors, gt_classes_one_hot_tensors, gt_box_tensors


def show_some_data():
    dummy_scores = np.array([1.0], dtype=np.float32)  # give boxes a score of 100%

    plt.figure(figsize=(30, 15))
    for idx in range(5):
      plt.subplot(2, 3, idx+1)
      plot_detections(
          train_images_np[idx],
          gt_boxes[idx],
          np.ones(shape=[gt_boxes[idx].shape[0]], dtype=np.int32),
          dummy_scores, category_index)
    plt.show()

train_image_tensors, gt_classes_one_hot_tensors, gt_box_tensors = load_data()
print("loaded ", len(train_image_tensors))

region classes: {'glass': 4987, 'plate': 310, 'cup': 1115}
no class for 15 regions
no region data for  00002.jpg338727
no region data for  00003.jpg301598
no region data for  00004.jpg294643
no region data for  00005.jpg299565
no region data for  00006.jpg305176
no region data for  00007.jpg301325
no region data for  00008.jpg303852
no region data for  00009.jpg287445
no region data for  00010.jpg312631
no region data for  00011.jpg328677
no region data for  00012.jpg342041
no region data for  00013.jpg342420
no region data for  00014.jpg327238
no region data for  00015.jpg338018
no region data for  00016.jpg336979
no region data for  00017.jpg344794
no region data for  00018.jpg356870
no region data for  00019.jpg365775
no region data for  00020.jpg345683
no region data for  00021.jpg341824
no region data for  00022.jpg334768
no region data for  00023.jpg315607
no region data for  00024.jpg324922
no region data for  00025.jpg312964
no region data for  00026.jpg343717
no region data fo

In [5]:
import tensorboard
tensorboard.__version__

'2.4.0'

In [14]:
# Download the checkpoint and put it into models/research/object_detection/test_data/

# !wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
# !tar -xf ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
# !if [ -d "test_data/checkpoint" ]; then rm -Rf test_data/checkpoint; fi
# !mkdir test_data/checkpoint
# !mv ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint test_data/

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [6]:
tf.keras.backend.clear_session()

print(tf.__version__)

print('Building model and restoring weights for fine-tuning...', flush=True)
num_classes = 3
pipeline_config = r'C:\Users\Acer\Desktop\lampix glass dettect\models\research\object_detection\configs\tf2\ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.config'
#pipeline_config = 'configs/tf2/ssd_mobilenet_v2_320x320_coco17_tpu-8.config'
#pipeline_config = 'configs/tf2/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.config'

checkpoint_path = r'C:\Users\Acer\Desktop\lampix glass dettect\models\research\object_detection\test_data\checkpoint\ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8\checkpoint\ckpt-0.index'

# This will be where we save checkpoint & config for TFLite conversion later.
output_directory = r'C:\Users\Acer\Desktop\lampix glass dettect\output'
output_checkpoint_dir = os.path.join(output_directory, 'checkpoint')

# Load pipeline config and build a detection model.
#
# Since we are working off of a COCO architecture which predicts 90
# class slots by default, we override the `num_classes` field here to be just
# one (for our new rubber ducky class).
configs = config_util.get_configs_from_pipeline_file(pipeline_config)
model_config = configs['model']
model_config.ssd.num_classes = num_classes
model_config.ssd.freeze_batchnorm = True
detection_model = model_builder.build(
      model_config=model_config, is_training=True)
# Save new pipeline config
pipeline_proto = config_util.create_pipeline_proto_from_configs(configs)
config_util.save_pipeline_config(pipeline_proto, output_directory)

# Set up object-based checkpoint restore --- SSD has two prediction
# `heads` --- one for classification, the other for box regression.  We will
# restore the box regression head but initialize the classification head
# from scratch (we show the omission below by commenting out the line that
# we would add if we wanted to restore both heads)
fake_box_predictor = tf.compat.v2.train.Checkpoint(
    _base_tower_layers_for_heads=detection_model._box_predictor._base_tower_layers_for_heads,
    # _prediction_heads=detection_model._box_predictor._prediction_heads,
    #    (i.e., the classification head that we *will not* restore)
    _box_prediction_head=detection_model._box_predictor._box_prediction_head,
    )
fake_model = tf.compat.v2.train.Checkpoint(
          _feature_extractor=detection_model._feature_extractor,
          _box_predictor=fake_box_predictor)
ckpt = tf.compat.v2.train.Checkpoint(model=fake_model)
ckpt.restore(checkpoint_path).expect_partial()

# To save checkpoint for TFLite conversion.
exported_ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt_manager = tf.train.CheckpointManager(
    exported_ckpt, output_checkpoint_dir, max_to_keep=1)

# Run model through a dummy image so that variables are created
image, shapes = detection_model.preprocess(tf.zeros([1, 320, 320, 3]))
prediction_dict = detection_model.predict(image, shapes)
_ = detection_model.postprocess(prediction_dict, shapes)
print('Weights restored!')

2.4.0
Building model and restoring weights for fine-tuning...
INFO:tensorflow:Writing pipeline config file to C:\Users\Acer\Desktop\lampix glass dettect\output\pipeline.config
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Weights restored!


In [11]:
tf.keras.backend.set_learning_phase(True)

# These parameters can be tuned; since our training set has 5 images
# it doesn't make sense to have a much larger batch size, though we could
# fit more examples in memory if we wanted to.
batch_size = 25
learning_rate = 1.0
num_batches = 300

# Select variables in top layers to fine-tune.
trainable_variables = detection_model.trainable_variables
to_fine_tune = []
prefixes_to_train = [
  'WeightSharedConvolutionalBoxPredictor/WeightSharedConvolutionalBoxHead',
  'WeightSharedConvolutionalBoxPredictor/WeightSharedConvolutionalClassHead']
for var in trainable_variables:
  if any([var.name.startswith(prefix) for prefix in prefixes_to_train]):
    to_fine_tune.append(var)

# Set up forward + backward pass for a single train step.
def get_model_train_step_function(model, optimizer, vars_to_fine_tune):
  """Get a tf.function for training step."""

  # Use tf.function for a bit of speed.
  # Comment out the tf.function decorator if you want the inside of the
  # function to run eagerly.
  @tf.function
  def train_step_fn(image_tensors,
                    groundtruth_boxes_list,
                    groundtruth_classes_list):
    """A single training iteration.

    Args:
      image_tensors: A list of [1, height, width, 3] Tensor of type tf.float32.
        Note that the height and width can vary across images, as they are
        reshaped within this function to be 320x320.
      groundtruth_boxes_list: A list of Tensors of shape [N_i, 4] with type
        tf.float32 representing groundtruth boxes for each image in the batch.
      groundtruth_classes_list: A list of Tensors of shape [N_i, num_classes]
        with type tf.float32 representing groundtruth boxes for each image in
        the batch.

    Returns:
      A scalar tensor representing the total loss for the input batch.
    """
    
    #print("img", image_tensors[0].shape)
    #print("boxes", groundtruth_boxes_list[0].shape)
    #print("classes", groundtruth_classes_list[0])
    
    shapes = tf.constant(batch_size * [[320, 320, 3]], dtype=tf.int32)
    model.provide_groundtruth(
        groundtruth_boxes_list=groundtruth_boxes_list,
        groundtruth_classes_list=groundtruth_classes_list)
    with tf.GradientTape() as tape:
      preprocessed_images = tf.concat(
          [detection_model.preprocess(image_tensor)[0]
           for image_tensor in image_tensors], axis=0)
      prediction_dict = model.predict(preprocessed_images, shapes)
      losses_dict = model.loss(prediction_dict, shapes)
      total_loss = losses_dict['Loss/localization_loss'] + losses_dict['Loss/classification_loss']
      gradients = tape.gradient(total_loss, vars_to_fine_tune)
      optimizer.apply_gradients(zip(gradients, vars_to_fine_tune))
    return total_loss

  return train_step_fn

optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.5)
train_step_fn = get_model_train_step_function(
    detection_model, optimizer, to_fine_tune)

print('Start fine-tuning!', flush=True)
for idx in range(num_batches):
  # Grab keys for a random subset of examples
  all_keys = list(range(len(train_image_tensors)))
  random.shuffle(all_keys)
  example_keys = all_keys[:batch_size]

  # Note that we do not do data augmentation in this demo.  If you want a
  # a fun exercise, we recommend experimenting with random horizontal flipping
  # and random cropping :)
  gt_boxes_list = [gt_box_tensors[key] for key in example_keys]
  gt_classes_list = [gt_classes_one_hot_tensors[key] for key in example_keys]
  image_tensors = [train_image_tensors[key] for key in example_keys]

  # Training step (forward pass + backwards pass)
  total_loss = train_step_fn(image_tensors, gt_boxes_list, gt_classes_list)

  if idx % 20 == 0:
    print('batch ' + str(idx) + ' of ' + str(num_batches)
    + ', loss=' +  str(total_loss.numpy()), flush=True)

print('Done fine-tuning!')
ckpt_manager.save()

print('Checkpoint saved!')

Start fine-tuning!
batch 0 of 300, loss=1.3804059
batch 20 of 300, loss=1.3875898
batch 40 of 300, loss=1.3767574
batch 60 of 300, loss=1.3871756
batch 80 of 300, loss=1.3677568
batch 100 of 300, loss=1.3477806
batch 120 of 300, loss=1.3843756


KeyboardInterrupt: 

In [9]:
images = [12, 23, 56, 23, 89, 3, 5, 8]
num_predictions = len(images)
image_tensors = []

img_files = glob.glob(r"C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\*.jpg")

for i in images:
    print(img_files[i])
    img = asarray(Image.open(img_files[i]))
    image_tensors = []
    image_tensors.append(tf.expand_dims(tf.convert_to_tensor(img, dtype=tf.float32), axis=0))

    #preprocessed_images = tf.concat(
    #  [detection_model.preprocess(image_tensor)[0] for image_tensor in image_tensors], axis=0)
    #shapes = tf.constant(num_predictions * [[320, 320, 3]], dtype=tf.int32)

    preprocessed_images, shapes = detection_model.preprocess(image_tensors[0])

    prediction_dict = detection_model.predict(preprocessed_images, shapes)

    result = detection_model.postprocess(prediction_dict, None)

    boxes = result["detection_boxes"]
    classes = result["detection_classes"]
    scores = result["detection_scores"]

    print(boxes[0].numpy(), classes[0].numpy(), scores[0].numpy())

    #ori_image = np.ones([360, 480, 3], dtype=np.int32) * 200
    #test_image = img.copy()
    #boxes = np.array(boxes, dtype=np.float32)
    #classes = np.array(classes, dtype=np.int32)
    #detections = np.ones(len(classes))
    test_image = img.copy()
    im = viz_utils.visualize_boxes_and_labels_on_image_array(
      test_image, boxes[0].numpy(), (classes[0].numpy() + 1).astype(int), scores[0].numpy(),
      category_index,
      use_normalized_coordinates=True,
      min_score_thresh=0.01)
    cv2.imwrite("img%d.jpg" % i, im)


C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\00014.jpg
[[0.         0.         0.11326203 0.07320088]
 [0.         0.00107234 0.11326203 0.12320088]
 [0.         0.05107234 0.11326203 0.17320089]
 [0.         0.10107234 0.11326203 0.22320089]
 [0.         0.15107234 0.11326203 0.2732009 ]
 [0.         0.20107234 0.11326203 0.32320088]
 [0.         0.25107235 0.11326203 0.3732009 ]
 [0.         0.30107236 0.11326203 0.4232009 ]
 [0.         0.35107237 0.11326203 0.47320092]
 [0.         0.40107232 0.11326203 0.52320087]
 [0.         0.4510723  0.11326203 0.5732008 ]
 [0.         0.5010723  0.11326203 0.6232009 ]
 [0.         0.5510723  0.11326203 0.6732009 ]
 [0.         0.6010723  0.11326203 0.7232009 ]
 [0.         0.6510723  0.11326203 0.7732008 ]
 [0.         0.7010724  0.11326203 0.8232009 ]
 [0.         0.7510723  0.11326203 0.8732009 ]
 [0.         0.8010723  0.11326203 0.9232009 ]
 [0.         0.8510723  0.11326203 0.9732009 ]
 [0.         0.9010723  0.11326203 1.        ]
 

C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\00058.jpg
[[0.         0.         0.11326203 0.07320088]
 [0.         0.00107234 0.11326203 0.12320088]
 [0.         0.05107234 0.11326203 0.17320089]
 [0.         0.10107234 0.11326203 0.22320089]
 [0.         0.15107234 0.11326203 0.2732009 ]
 [0.         0.20107234 0.11326203 0.32320088]
 [0.         0.25107235 0.11326203 0.3732009 ]
 [0.         0.30107236 0.11326203 0.4232009 ]
 [0.         0.35107237 0.11326203 0.47320092]
 [0.         0.40107232 0.11326203 0.52320087]
 [0.         0.4510723  0.11326203 0.5732008 ]
 [0.         0.5010723  0.11326203 0.6232009 ]
 [0.         0.5510723  0.11326203 0.6732009 ]
 [0.         0.6010723  0.11326203 0.7232009 ]
 [0.         0.6510723  0.11326203 0.7732008 ]
 [0.         0.7010724  0.11326203 0.8232009 ]
 [0.         0.7510723  0.11326203 0.8732009 ]
 [0.         0.8010723  0.11326203 0.9232009 ]
 [0.         0.8510723  0.11326203 0.9732009 ]
 [0.         0.9010723  0.11326203 1.        ]
 

C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\00091.jpg
[[0.         0.         0.11326203 0.07320088]
 [0.         0.00107234 0.11326203 0.12320088]
 [0.         0.05107234 0.11326203 0.17320089]
 [0.         0.10107234 0.11326203 0.22320089]
 [0.         0.15107234 0.11326203 0.2732009 ]
 [0.         0.20107234 0.11326203 0.32320088]
 [0.         0.25107235 0.11326203 0.3732009 ]
 [0.         0.30107236 0.11326203 0.4232009 ]
 [0.         0.35107237 0.11326203 0.47320092]
 [0.         0.40107232 0.11326203 0.52320087]
 [0.         0.4510723  0.11326203 0.5732008 ]
 [0.         0.5010723  0.11326203 0.6232009 ]
 [0.         0.5510723  0.11326203 0.6732009 ]
 [0.         0.6010723  0.11326203 0.7232009 ]
 [0.         0.6510723  0.11326203 0.7732008 ]
 [0.         0.7010724  0.11326203 0.8232009 ]
 [0.         0.7510723  0.11326203 0.8732009 ]
 [0.         0.8010723  0.11326203 0.9232009 ]
 [0.         0.8510723  0.11326203 0.9732009 ]
 [0.         0.9010723  0.11326203 1.        ]
 

C:\Users\Acer\Desktop\lampix glass dettect\TDB_M\00007.jpg
[[0.         0.         0.11326203 0.07320088]
 [0.         0.00107234 0.11326203 0.12320088]
 [0.         0.05107234 0.11326203 0.17320089]
 [0.         0.10107234 0.11326203 0.22320089]
 [0.         0.15107234 0.11326203 0.2732009 ]
 [0.         0.20107234 0.11326203 0.32320088]
 [0.         0.25107235 0.11326203 0.3732009 ]
 [0.         0.30107236 0.11326203 0.4232009 ]
 [0.         0.35107237 0.11326203 0.47320092]
 [0.         0.40107232 0.11326203 0.52320087]
 [0.         0.4510723  0.11326203 0.5732008 ]
 [0.         0.5010723  0.11326203 0.6232009 ]
 [0.         0.5510723  0.11326203 0.6732009 ]
 [0.         0.6010723  0.11326203 0.7232009 ]
 [0.         0.6510723  0.11326203 0.7732008 ]
 [0.         0.7010724  0.11326203 0.8232009 ]
 [0.         0.7510723  0.11326203 0.8732009 ]
 [0.         0.8010723  0.11326203 0.9232009 ]
 [0.         0.8510723  0.11326203 0.9732009 ]
 [0.         0.9010723  0.11326203 1.        ]
 

In [10]:
scores[0].numpy() > 0.01

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [1]:
cv2.imshow("img%d.jpg" % 100, im)

NameError: name 'cv2' is not defined